using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]

public partial class syncScreamModel
{
    [RealtimeProperty(265, true, true)]
    private bool _scream;
    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {

    }
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class syncScreamModel : IModel {
    // Properties
    public bool scream {
        get { return _cache.LookForValueInCache(_scream, entry => entry.screamSet, entry => entry.scream); }
        set { if (value == scream) return; _cache.UpdateLocalCache(entry => { entry.screamSet = true; entry.scream = value; return entry; }); FireScreamDidChange(value); }
    }
    
    // Events
    public delegate void ScreamDidChange(syncScreamModel model, bool value);
    public event         ScreamDidChange screamDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool screamSet;
        public bool scream;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public syncScreamModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireScreamDidChange(bool value) {
        try {
            if (screamDidChange != null)
                screamDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        Scream = 265,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _scream = scream;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Scream, _scream ? 1u : 0u);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.screamSet)
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.Scream, entry.scream ? 1u : 0u);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteVarint32((uint)PropertyID.Scream, _scream ? 1u : 0u);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.screamSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.screamSet)
                    stream.WriteVarint32((uint)PropertyID.Scream, entry.scream ? 1u : 0u);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool screamExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.screamSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Scream: {
                    bool previousValue = _scream;
                    
                    _scream = (stream.ReadVarint32() != 0);
                    
                    if (!screamExistsInChangeCache && _scream != previousValue)
                        FireScreamDidChange(_scream);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
